#!/usr/bin/env node
/**
 * build-skills.js
 * Reads SKILL.md files from skillforge-ai and writes them
 * to builder/skills.js as a separate loadable module.
 * This avoids HTML injection issues entirely.
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

function loadSkill(name) {
  const paths = [
    join(rootDir, 'node_modules', 'skillforge-ai', 'dist', 'skills', name, 'SKILL.md'),
  ];
  for (const p of paths) {
    try { return readFileSync(p, 'utf-8'); } catch {}
  }
  return null;
}

const SKILLS = ['frontend-design', 'chart-js', 'fintech-ui', 'api-integration', 'zca-schema', 'llm-integration'];

console.log('🔧 Building skills from skillforge-ai...\n');

const skillContents = {};
for (const skill of SKILLS) {
  const content = loadSkill(skill);
  if (!content) { console.error(`❌ Missing: ${skill}`); process.exit(1); }
  skillContents[skill] = content;
  console.log(`  ✓ ${skill} (${content.length} chars)`);
}

let version = '1.1.0';
try {
  version = JSON.parse(readFileSync(
    join(rootDir, 'node_modules/skillforge-ai/dist/package.json'), 'utf-8'
  )).version;
} catch {}

// Write as a standalone JS file — no HTML injection needed
const output = [
  `// Auto-generated by scripts/build-skills.js`,
  `// Source: skillforge-ai@${version}`,
  `// Generated: ${new Date().toISOString()}`,
  `// DO NOT EDIT — run npm run build:skills to regenerate`,
  ``,
  `window.SKILLFORGE_VERSION = ${JSON.stringify(version)};`,
  `window.SKILL_CONTENTS = ${JSON.stringify(skillContents, null, 2)};`,
].join('\n');

const outPath = join(rootDir, 'builder', 'skills.js');
writeFileSync(outPath, output);

const total = Object.values(skillContents).reduce((a, c) => a + c.length, 0);
console.log(`\n✅ Written to builder/skills.js`);
console.log(`   skillforge-ai@${version}`);
console.log(`   ${total.toLocaleString()} chars across ${SKILLS.length} skills\n`);
